### ISSUE TITLE
qiskit-sim for dummies

### ISSUE THREAD

**Issue by omarcostahamido** [Qiskit/qiskit-js#58]
### What is the expected behavior?
I wanted to be able to just run a couple circuits with the [qiskit-sim](https://github.com/Qiskit/qiskit-js/tree/master/packages/qiskit-sim), but I am not able to completely understand how to work with it. I can see that we can query the state of the circuit which is fine - i.e. it gives us the equivalent to the aggregated results from IBM QX.
However, if I want to run this circuit for a different number of shots, how can I do it?
Also, and actually more importantly, how can I add a measurement gate? Is there an equivalent classical register here?
I am sorry if these questions sound very basic. I am really enjoying learning this!

Best,
OCH

**Comment by jesusprubio** [comment]
The qiskit-sim is a very basic simulator not related with IBM QX or QASM. We've used it in specific projects but it's not similar to the Qiskit (or IBM QX) official one.

Eventually the idea is to add the same one, which is written in C++, compiled to webassembly. In this way we could have exactly the same behavior in the browser.

**Comment by omarcostahamido** [comment]
Thank you for the clarification.

O
